# This file has been generated by node2nix 1.11.1. Do not edit!
{
  nodeEnv,
  fetchurl,
  nix-gitignore,
  stdenv,
  lib,
  globalBuildInputs ? [],
}: let
  sources = {
    "@aws-crypto/crc32-5.2.0" = {
      name = "_at_aws-crypto_slash_crc32";
      packageName = "@aws-crypto/crc32";
      version = "5.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@aws-crypto/crc32/-/crc32-5.2.0.tgz";
        sha512 = "nLbCWqQNgUiwwtFsen1AdzAtvuLRsQS8rYgMuxCrdKf9kOssamGLuPwyTY9wyYblNr9+1XM8v6zoDTPPSIeANg==";
      };
    };
    "@aws-crypto/util-5.2.0" = {
      name = "_at_aws-crypto_slash_util";
      packageName = "@aws-crypto/util";
      version = "5.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@aws-crypto/util/-/util-5.2.0.tgz";
        sha512 = "4RkU9EsI6ZpBve5fseQlGNUWKMa1RLPQ1dnjnQoe07ldfIzcsGb5hC5W0Dm7u423KWzawlrpbjXBrXCEv9zazQ==";
      };
    };
    "@aws-sdk/types-3.731.0" = {
      name = "_at_aws-sdk_slash_types";
      packageName = "@aws-sdk/types";
      version = "3.731.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@aws-sdk/types/-/types-3.731.0.tgz";
        sha512 = "NrdkJg6oOUbXR2r9WvHP408CLyvST8cJfp1/jP9pemtjvjPoh6NukbCtiSFdOOb1eryP02CnqQWItfJC1p2Y/Q==";
      };
    };
    "@mlabs-haskell/cardano-data-lite-git+ssh://git@github.com/mlabs-haskell/cardano-data-lite.git#01274415829dc56d3b136b33c27d614a5e53e71f" = {
      name = "_at_mlabs-haskell_slash_cardano-data-lite";
      packageName = "@mlabs-haskell/cardano-data-lite";
      version = "1.0.0";
      src = builtins.fetchGit {
        url = "ssh://git@github.com/mlabs-haskell/cardano-data-lite.git";
        rev = "01274415829dc56d3b136b33c27d614a5e53e71f";
      };
    };
    "@mlabs-haskell/json-bigint-2.0.0" = {
      name = "_at_mlabs-haskell_slash_json-bigint";
      packageName = "@mlabs-haskell/json-bigint";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@mlabs-haskell/json-bigint/-/json-bigint-2.0.0.tgz";
        sha512 = "JX9TON+nZbt+1TJ5MNV1Gcpxp3/m56x1/glDwzGtydrzQzyZbKg4XFw9Frib6fh89YVqjSFJ9xmVeIyDJ5DxTQ==";
      };
    };
    "@noble/ed25519-2.2.3" = {
      name = "_at_noble_slash_ed25519";
      packageName = "@noble/ed25519";
      version = "2.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@noble/ed25519/-/ed25519-2.2.3.tgz";
        sha512 = "iHV8eI2mRcUmOx159QNrU8vTpQ/Xm70yJ2cTk3Trc86++02usfqFoNl6x0p3JN81ZDS/1gx6xiK0OwrgqCT43g==";
      };
    };
    "@noble/hashes-1.7.1" = {
      name = "_at_noble_slash_hashes";
      packageName = "@noble/hashes";
      version = "1.7.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@noble/hashes/-/hashes-1.7.1.tgz";
        sha512 = "B8XBPsn4vT/KJAGqDzbwztd+6Yte3P4V7iafm24bxgDe/mlRuK6xmWPuCNrKt2vDafZ8MfJLlchDG/vYafQEjQ==";
      };
    };
    "@smithy/is-array-buffer-2.2.0" = {
      name = "_at_smithy_slash_is-array-buffer";
      packageName = "@smithy/is-array-buffer";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@smithy/is-array-buffer/-/is-array-buffer-2.2.0.tgz";
        sha512 = "GGP3O9QFD24uGeAXYUjwSTXARoqpZykHadOmA8G5vfJPK0/DC67qa//0qvqrJzL1xc8WQWX7/yc7fwudjPHPhA==";
      };
    };
    "@smithy/types-4.1.0" = {
      name = "_at_smithy_slash_types";
      packageName = "@smithy/types";
      version = "4.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@smithy/types/-/types-4.1.0.tgz";
        sha512 = "enhjdwp4D7CXmwLtD6zbcDMbo6/T6WtuuKCY49Xxc6OMOmUWlBEBDREsxxgV2LIdeQPW756+f97GzcgAwp3iLw==";
      };
    };
    "@smithy/util-buffer-from-2.2.0" = {
      name = "_at_smithy_slash_util-buffer-from";
      packageName = "@smithy/util-buffer-from";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@smithy/util-buffer-from/-/util-buffer-from-2.2.0.tgz";
        sha512 = "IJdWBbTcMQ6DA0gdNhh/BwrLkDR+ADW5Kr1aZmd4k3DIF6ezMV4R2NIAmT08wQJ3yUK82thHWmC/TnK/wpMMIA==";
      };
    };
    "@smithy/util-utf8-2.3.0" = {
      name = "_at_smithy_slash_util-utf8";
      packageName = "@smithy/util-utf8";
      version = "2.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@smithy/util-utf8/-/util-utf8-2.3.0.tgz";
        sha512 = "R8Rdn8Hy72KKcebgLiv8jQcQkXoLMOGGv5uI1/k0l+snqkOzQ1R0ChUBCxWMlBsFMekWjq0wRudIweFs7sKT5A==";
      };
    };
    "@textlint/ast-node-types-12.6.1" = {
      name = "_at_textlint_slash_ast-node-types";
      packageName = "@textlint/ast-node-types";
      version = "12.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@textlint/ast-node-types/-/ast-node-types-12.6.1.tgz";
        sha512 = "uzlJ+ZsCAyJm+lBi7j0UeBbj+Oy6w/VWoGJ3iHRHE5eZ8Z4iK66mq+PG/spupmbllLtz77OJbY89BYqgFyjXmA==";
      };
    };
    "@textlint/markdown-to-ast-12.6.1" = {
      name = "_at_textlint_slash_markdown-to-ast";
      packageName = "@textlint/markdown-to-ast";
      version = "12.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@textlint/markdown-to-ast/-/markdown-to-ast-12.6.1.tgz";
        sha512 = "T0HO+VrU9VbLRiEx/kH4+gwGMHNMIGkp0Pok+p0I33saOOLyhfGvwOKQgvt2qkxzQEV2L5MtGB8EnW4r5d3CqQ==";
      };
    };
    "@types/mdast-3.0.15" = {
      name = "_at_types_slash_mdast";
      packageName = "@types/mdast";
      version = "3.0.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/mdast/-/mdast-3.0.15.tgz";
        sha512 = "LnwD+mUEfxWMa1QpDraczIn6k0Ee3SMicuYSSzS6ZYl2gKS09EClnJYGd8Du6rfc5r/GZEk5o1mRb8TaTj03sQ==";
      };
    };
    "@types/unist-2.0.10" = {
      name = "_at_types_slash_unist";
      packageName = "@types/unist";
      version = "2.0.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/unist/-/unist-2.0.10.tgz";
        sha512 = "IfYcSBWE3hLpBg8+X2SEa8LVkJdJEkT2Ese2aaLs3ptGdVtABxndrMaxuFlQ1qdFf9Q5rDvDpxI3WwgvKFAsQA==";
      };
    };
    "anchor-markdown-header-0.6.0" = {
      name = "anchor-markdown-header";
      packageName = "anchor-markdown-header";
      version = "0.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/anchor-markdown-header/-/anchor-markdown-header-0.6.0.tgz";
        sha512 = "v7HJMtE1X7wTpNFseRhxsY/pivP4uAJbidVhPT+yhz4i/vV1+qx371IXuV9V7bN6KjFtheLJxqaSm0Y/8neJTA==";
      };
    };
    "array-buffer-byte-length-1.0.1" = {
      name = "array-buffer-byte-length";
      packageName = "array-buffer-byte-length";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/array-buffer-byte-length/-/array-buffer-byte-length-1.0.1.tgz";
        sha512 = "ahC5W1xgou+KTXix4sAO8Ki12Q+jf4i0+tmk3sC+zgcynshkHxzpXdImBehiUYKKKDwvfFiJl1tZt6ewscS1Mg==";
      };
    };
    "arraybuffer.prototype.slice-1.0.3" = {
      name = "arraybuffer.prototype.slice";
      packageName = "arraybuffer.prototype.slice";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/arraybuffer.prototype.slice/-/arraybuffer.prototype.slice-1.0.3.tgz";
        sha512 = "bMxMKAjg13EBSVscxTaYA4mRc5t1UAXa2kXiGTNfZ079HIWXEkKmkgFrh/nJqamaLSrXO5H4WFFkPEaLJWbs3A==";
      };
    };
    "available-typed-arrays-1.0.7" = {
      name = "available-typed-arrays";
      packageName = "available-typed-arrays";
      version = "1.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/available-typed-arrays/-/available-typed-arrays-1.0.7.tgz";
        sha512 = "wvUjBtSGN7+7SjNpq/9M2Tg350UZD3q62IFZLbRAR1bSMlCo1ZaeW+BJ+D090e4hIIZLBcTDWe4Mh4jvUDajzQ==";
      };
    };
    "bail-1.0.5" = {
      name = "bail";
      packageName = "bail";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/bail/-/bail-1.0.5.tgz";
        sha512 = "xFbRxM1tahm08yHBP16MMjVUAvDaBMD38zsM9EMAUN61omwLmKlOpB/Zku5QkjZ8TZ4vn53pj+t518cH0S03RQ==";
      };
    };
    "base58-js-2.0.0" = {
      name = "base58-js";
      packageName = "base58-js";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/base58-js/-/base58-js-2.0.0.tgz";
        sha512 = "nAV5d32QXuGcGptSApkKpC1gGakWBnfJMNjKrYTBh4tb0szfZF+ooueFLy8T4VrY+o4SrE/TyrtUnRZcwZchaA==";
      };
    };
    "bech32-2.0.0" = {
      name = "bech32";
      packageName = "bech32";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/bech32/-/bech32-2.0.0.tgz";
        sha512 = "LcknSilhIGatDAsY1ak2I8VtGaHNhgMSYVxFrGLXv+xLHytaKZKcaUJJUE7qmBr7h33o5YQwP55pMI0xmkpJwg==";
      };
    };
    "call-bind-1.0.7" = {
      name = "call-bind";
      packageName = "call-bind";
      version = "1.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/call-bind/-/call-bind-1.0.7.tgz";
        sha512 = "GHTSNSYICQ7scH7sZ+M2rFopRoLh8t2bLSW6BbgrtLsahOIB5iyAVJf9GjWK3cYTDaMj4XdBpM1cA6pIS0Kv2w==";
      };
    };
    "ccount-1.1.0" = {
      name = "ccount";
      packageName = "ccount";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ccount/-/ccount-1.1.0.tgz";
        sha512 = "vlNK021QdI7PNeiUh/lKkC/mNHHfV0m/Ad5JoI0TYtlBnJAslM/JIkm/tGC88bkLIwO6OQ5uV6ztS6kVAtCDlg==";
      };
    };
    "character-entities-1.2.4" = {
      name = "character-entities";
      packageName = "character-entities";
      version = "1.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/character-entities/-/character-entities-1.2.4.tgz";
        sha512 = "iBMyeEHxfVnIakwOuDXpVkc54HijNgCyQB2w0VfGQThle6NXn50zU6V/u+LDhxHcDUPojn6Kpga3PTAD8W1bQw==";
      };
    };
    "character-entities-legacy-1.1.4" = {
      name = "character-entities-legacy";
      packageName = "character-entities-legacy";
      version = "1.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/character-entities-legacy/-/character-entities-legacy-1.1.4.tgz";
        sha512 = "3Xnr+7ZFS1uxeiUDvV02wQ+QDbc55o97tIV5zHScSPJpcLm/r0DFPcoY3tYRp+VZukxuMeKgXYmsXQHO05zQeA==";
      };
    };
    "character-reference-invalid-1.1.4" = {
      name = "character-reference-invalid";
      packageName = "character-reference-invalid";
      version = "1.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/character-reference-invalid/-/character-reference-invalid-1.1.4.tgz";
        sha512 = "mKKUkUbhPpQlCOfIuZkvSEgktjPFIsZKRRbC6KWVEMvlzblj3i3asQv5ODsrwt0N3pHAEvjP8KTQPHkp0+6jOg==";
      };
    };
    "data-view-buffer-1.0.1" = {
      name = "data-view-buffer";
      packageName = "data-view-buffer";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/data-view-buffer/-/data-view-buffer-1.0.1.tgz";
        sha512 = "0lht7OugA5x3iJLOWFhWK/5ehONdprk0ISXqVFn/NFrDu+cuc8iADFrGQz5BnRK7LLU3JmkbXSxaqX+/mXYtUA==";
      };
    };
    "data-view-byte-length-1.0.1" = {
      name = "data-view-byte-length";
      packageName = "data-view-byte-length";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/data-view-byte-length/-/data-view-byte-length-1.0.1.tgz";
        sha512 = "4J7wRJD3ABAzr8wP+OcIcqq2dlUKp4DVflx++hs5h5ZKydWMI6/D/fAot+yh6g2tHh8fLFTvNOaVN357NvSrOQ==";
      };
    };
    "data-view-byte-offset-1.0.0" = {
      name = "data-view-byte-offset";
      packageName = "data-view-byte-offset";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/data-view-byte-offset/-/data-view-byte-offset-1.0.0.tgz";
        sha512 = "t/Ygsytq+R995EJ5PZlD4Cu56sWa8InXySaViRzw9apusqsOO2bQP+SbYzAhR0pFKoB+43lYy8rWban9JSuXnA==";
      };
    };
    "debug-4.3.6" = {
      name = "debug";
      packageName = "debug";
      version = "4.3.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-4.3.6.tgz";
        sha512 = "O/09Bd4Z1fBrU4VzkhFqVgpPzaGbw6Sm9FEkBT1A/YBXQFGuuSxa1dN2nxgxS34JmKXqYx8CZAwEVoJFImUXIg==";
      };
    };
    "define-data-property-1.1.4" = {
      name = "define-data-property";
      packageName = "define-data-property";
      version = "1.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/define-data-property/-/define-data-property-1.1.4.tgz";
        sha512 = "rBMvIzlpA8v6E+SJZoo++HAYqsLrkg7MSfIinMPFhmkorw7X+dOXVJQs+QT69zGkzMyfDnIMN2Wid1+NbL3T+A==";
      };
    };
    "define-properties-1.2.1" = {
      name = "define-properties";
      packageName = "define-properties";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/define-properties/-/define-properties-1.2.1.tgz";
        sha512 = "8QmQKqEASLd5nx0U1B1okLElbUuuttJ/AnYmRXbbbGDWh6uS208EjD4Xqq/I9wK7u0v6O08XhTWnt5XtEbR6Dg==";
      };
    };
    "doctoc-2.2.1" = {
      name = "doctoc";
      packageName = "doctoc";
      version = "2.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/doctoc/-/doctoc-2.2.1.tgz";
        sha512 = "qNJ1gsuo7hH40vlXTVVrADm6pdg30bns/Mo7Nv1SxuXSM1bwF9b4xQ40a6EFT/L1cI+Yylbyi8MPI4G4y7XJzQ==";
      };
    };
    "dom-serializer-1.4.1" = {
      name = "dom-serializer";
      packageName = "dom-serializer";
      version = "1.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/dom-serializer/-/dom-serializer-1.4.1.tgz";
        sha512 = "VHwB3KfrcOOkelEG2ZOfxqLZdfkil8PtJi4P8N2MMXucZq2yLp75ClViUlOVwyoHEDjYU433Aq+5zWP61+RGag==";
      };
    };
    "domelementtype-2.3.0" = {
      name = "domelementtype";
      packageName = "domelementtype";
      version = "2.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/domelementtype/-/domelementtype-2.3.0.tgz";
        sha512 = "OLETBj6w0OsagBwdXnPdN0cnMfF9opN69co+7ZrbfPGrdpPVNBUj02spi6B1N7wChLQiPn4CSH/zJvXw56gmHw==";
      };
    };
    "domhandler-4.3.1" = {
      name = "domhandler";
      packageName = "domhandler";
      version = "4.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/domhandler/-/domhandler-4.3.1.tgz";
        sha512 = "GrwoxYN+uWlzO8uhUXRl0P+kHE4GtVPfYzVLcUxPL7KNdHKj66vvlhiweIHqYYXWlw+T8iLMp42Lm67ghw4WMQ==";
      };
    };
    "domutils-2.8.0" = {
      name = "domutils";
      packageName = "domutils";
      version = "2.8.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/domutils/-/domutils-2.8.0.tgz";
        sha512 = "w96Cjofp72M5IIhpjgobBimYEfoPjx1Vx0BSX9P30WBdZW2WIKU0T1Bd0kz2eNZ9ikjKgHbEyKx8BB6H1L3h3A==";
      };
    };
    "emoji-regex-10.1.0" = {
      name = "emoji-regex";
      packageName = "emoji-regex";
      version = "10.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/emoji-regex/-/emoji-regex-10.1.0.tgz";
        sha512 = "xAEnNCT3w2Tg6MA7ly6QqYJvEoY1tm9iIjJ3yMKK9JPlWuRHAMoe5iETwQnx3M9TVbFMfsrBgWKR+IsmswwNjg==";
      };
    };
    "entities-2.2.0" = {
      name = "entities";
      packageName = "entities";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/entities/-/entities-2.2.0.tgz";
        sha512 = "p92if5Nz619I0w+akJrLZH0MX0Pb5DX39XOwQTtXSdQQOaYH03S1uIQp4mhOZtAXrxq4ViO67YTiLBo2638o9A==";
      };
    };
    "entities-3.0.1" = {
      name = "entities";
      packageName = "entities";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/entities/-/entities-3.0.1.tgz";
        sha512 = "WiyBqoomrwMdFG1e0kqvASYfnlb0lp8M5o5Fw2OFq1hNZxxcNk8Ik0Xm7LxzBhuidnZB/UtBqVCgUz3kBOP51Q==";
      };
    };
    "es-abstract-1.23.3" = {
      name = "es-abstract";
      packageName = "es-abstract";
      version = "1.23.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/es-abstract/-/es-abstract-1.23.3.tgz";
        sha512 = "e+HfNH61Bj1X9/jLc5v1owaLYuHdeHHSQlkhCBiTK8rBvKaULl/beGMxwrMXjpYrv4pz22BlY570vVePA2ho4A==";
      };
    };
    "es-define-property-1.0.0" = {
      name = "es-define-property";
      packageName = "es-define-property";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/es-define-property/-/es-define-property-1.0.0.tgz";
        sha512 = "jxayLKShrEqqzJ0eumQbVhTYQM27CfT1T35+gCgDFoL82JLsXqTJ76zv6A0YLOgEnLUMvLzsDsGIrl8NFpT2gQ==";
      };
    };
    "es-errors-1.3.0" = {
      name = "es-errors";
      packageName = "es-errors";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/es-errors/-/es-errors-1.3.0.tgz";
        sha512 = "Zf5H2Kxt2xjTvbJvP2ZWLEICxA6j+hAmMzIlypy4xcBg1vKVnx89Wy0GbS+kf5cwCVFFzdCFh2XSCFNULS6csw==";
      };
    };
    "es-object-atoms-1.0.0" = {
      name = "es-object-atoms";
      packageName = "es-object-atoms";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/es-object-atoms/-/es-object-atoms-1.0.0.tgz";
        sha512 = "MZ4iQ6JwHOBQjahnjwaC1ZtIBH+2ohjamzAO3oaHcXYup7qxjF2fixyH+Q71voWHeOkI2q/TnJao/KfXYIZWbw==";
      };
    };
    "es-set-tostringtag-2.0.3" = {
      name = "es-set-tostringtag";
      packageName = "es-set-tostringtag";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/es-set-tostringtag/-/es-set-tostringtag-2.0.3.tgz";
        sha512 = "3T8uNMC3OQTHkFUsFq8r/BwAXLHvU/9O9mE0fBc/MY5iq/8H7ncvO947LmYA6ldWw9Uh8Yhf25zu6n7nML5QWQ==";
      };
    };
    "es-to-primitive-1.2.1" = {
      name = "es-to-primitive";
      packageName = "es-to-primitive";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/es-to-primitive/-/es-to-primitive-1.2.1.tgz";
        sha512 = "QCOllgZJtaUo9miYBcLChTUaHNjJF3PYs1VidD7AwiEj1kYxKeQTctLAezAOH5ZKRH0g2IgPn6KwB4IT8iRpvA==";
      };
    };
    "escape-string-regexp-4.0.0" = {
      name = "escape-string-regexp";
      packageName = "escape-string-regexp";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/escape-string-regexp/-/escape-string-regexp-4.0.0.tgz";
        sha512 = "TtpcNJ3XAzx3Gq8sWRzJaVajRs0uVxA2YAkdb1jm2YkPz4G6egUFAyA3n5vtEIZefPk5Wa4UXbKuS5fKkJWdgA==";
      };
    };
    "extend-3.0.2" = {
      name = "extend";
      packageName = "extend";
      version = "3.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/extend/-/extend-3.0.2.tgz";
        sha512 = "fjquC59cD7CyW6urNXK0FBufkZcoiGG80wTuPujX590cB5Ttln20E2UB4S/WARVqhXffZl2LNgS+gQdPIIim/g==";
      };
    };
    "fault-1.0.4" = {
      name = "fault";
      packageName = "fault";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/fault/-/fault-1.0.4.tgz";
        sha512 = "CJ0HCB5tL5fYTEA7ToAq5+kTwd++Borf1/bifxd9iT70QcXr4MRrO3Llf8Ifs70q+SJcGHFtnIE/Nw6giCtECA==";
      };
    };
    "for-each-0.3.3" = {
      name = "for-each";
      packageName = "for-each";
      version = "0.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/for-each/-/for-each-0.3.3.tgz";
        sha512 = "jqYfLp7mo9vIyQf8ykW2v7A+2N4QjeCeI5+Dz9XraiO1ign81wjiH7Fb9vSOWvQfNtmSa4H2RoQTrrXivdUZmw==";
      };
    };
    "format-0.2.2" = {
      name = "format";
      packageName = "format";
      version = "0.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/format/-/format-0.2.2.tgz";
        sha512 = "wzsgA6WOq+09wrU1tsJ09udeR/YZRaeArL9e1wPbFg3GG2yDnC2ldKpxs4xunpFF9DgqCqOIra3bc1HWrJ37Ww==";
      };
    };
    "function-bind-1.1.2" = {
      name = "function-bind";
      packageName = "function-bind";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/function-bind/-/function-bind-1.1.2.tgz";
        sha512 = "7XHNxH7qX9xG5mIwxkhumTox/MIRNcOgDrxWsMt2pAr23WHp6MrRlN7FBSFpCpr+oVO0F744iUgR82nJMfG2SA==";
      };
    };
    "function.prototype.name-1.1.6" = {
      name = "function.prototype.name";
      packageName = "function.prototype.name";
      version = "1.1.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/function.prototype.name/-/function.prototype.name-1.1.6.tgz";
        sha512 = "Z5kx79swU5P27WEayXM1tBi5Ze/lbIyiNgU3qyXUOf9b2rgXYyF9Dy9Cx+IQv/Lc8WCG6L82zwUPpSS9hGehIg==";
      };
    };
    "functions-have-names-1.2.3" = {
      name = "functions-have-names";
      packageName = "functions-have-names";
      version = "1.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/functions-have-names/-/functions-have-names-1.2.3.tgz";
        sha512 = "xckBUXyTIqT97tq2x2AMb+g163b5JFysYk0x4qxNFwbfQkmNZoiRHb6sPzI9/QV33WeuvVYBUIiD4NzNIyqaRQ==";
      };
    };
    "get-intrinsic-1.2.4" = {
      name = "get-intrinsic";
      packageName = "get-intrinsic";
      version = "1.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/get-intrinsic/-/get-intrinsic-1.2.4.tgz";
        sha512 = "5uYhsJH8VJBTv7oslg4BznJYhDoRI6waYCxMmCdnTrcCrHA/fCFKoTFz2JKKE0HdDFUF7/oQuhzumXJK7paBRQ==";
      };
    };
    "get-symbol-description-1.0.2" = {
      name = "get-symbol-description";
      packageName = "get-symbol-description";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/get-symbol-description/-/get-symbol-description-1.0.2.tgz";
        sha512 = "g0QYk1dZBxGwk+Ngc+ltRH2IBp2f7zBkBMBJZCDerh6EhlhSR6+9irMCuT/09zD6qkarHUSn529sK/yL4S27mg==";
      };
    };
    "globalthis-1.0.4" = {
      name = "globalthis";
      packageName = "globalthis";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/globalthis/-/globalthis-1.0.4.tgz";
        sha512 = "DpLKbNU4WylpxJykQujfCcwYWiV/Jhm50Goo0wrVILAv5jOr9d+H+UR3PhSCD2rCCEIg0uc+G+muBTwD54JhDQ==";
      };
    };
    "gopd-1.0.1" = {
      name = "gopd";
      packageName = "gopd";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/gopd/-/gopd-1.0.1.tgz";
        sha512 = "d65bNlIadxvpb/A2abVdlqKqV563juRnZ1Wtk6s1sIR8uNsXR70xqIzVqxVf1eTqDunwT2MkczEeaezCKTZhwA==";
      };
    };
    "has-bigints-1.0.2" = {
      name = "has-bigints";
      packageName = "has-bigints";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-bigints/-/has-bigints-1.0.2.tgz";
        sha512 = "tSvCKtBr9lkF0Ex0aQiP9N+OpV4zi2r/Nee5VkRDbaqv35RLYMzbwQfFSZZH0kR+Rd6302UJZ2p/bJCEoR3VoQ==";
      };
    };
    "has-property-descriptors-1.0.2" = {
      name = "has-property-descriptors";
      packageName = "has-property-descriptors";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-property-descriptors/-/has-property-descriptors-1.0.2.tgz";
        sha512 = "55JNKuIW+vq4Ke1BjOTjM2YctQIvCT7GFzHwmfZPGo5wnrgkid0YQtnAleFSqumZm4az3n2BS+erby5ipJdgrg==";
      };
    };
    "has-proto-1.0.3" = {
      name = "has-proto";
      packageName = "has-proto";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-proto/-/has-proto-1.0.3.tgz";
        sha512 = "SJ1amZAJUiZS+PhsVLf5tGydlaVB8EdFpaSO4gmiUKUOxk8qzn5AIy4ZeJUmh22znIdk/uMAUT2pl3FxzVUH+Q==";
      };
    };
    "has-symbols-1.0.3" = {
      name = "has-symbols";
      packageName = "has-symbols";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-symbols/-/has-symbols-1.0.3.tgz";
        sha512 = "l3LCuF6MgDNwTDKkdYGEihYjt5pRPbEg46rtlmnSPlUbgmB8LOIrKJbYYFBSbnPaJexMKtiPO8hmeRjRz2Td+A==";
      };
    };
    "has-tostringtag-1.0.2" = {
      name = "has-tostringtag";
      packageName = "has-tostringtag";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-tostringtag/-/has-tostringtag-1.0.2.tgz";
        sha512 = "NqADB8VjPFLM2V0VvHUewwwsw0ZWBaIdgo+ieHtK3hasLz4qeCRjYcqfB6AQrBggRKppKF8L52/VqdVsO47Dlw==";
      };
    };
    "hasown-2.0.2" = {
      name = "hasown";
      packageName = "hasown";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/hasown/-/hasown-2.0.2.tgz";
        sha512 = "0hJU9SCPvmMzIBdZFqNPXWa6dqh7WdH0cII9y+CyS8rG3nL48Bclra9HmKhVVUHyPWNH5Y7xDwAB7bfgSjkUMQ==";
      };
    };
    "htmlparser2-7.2.0" = {
      name = "htmlparser2";
      packageName = "htmlparser2";
      version = "7.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/htmlparser2/-/htmlparser2-7.2.0.tgz";
        sha512 = "H7MImA4MS6cw7nbyURtLPO1Tms7C5H602LRETv95z1MxO/7CP7rDVROehUYeYBUYEON94NXXDEPmZuq+hX4sog==";
      };
    };
    "internal-slot-1.0.7" = {
      name = "internal-slot";
      packageName = "internal-slot";
      version = "1.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/internal-slot/-/internal-slot-1.0.7.tgz";
        sha512 = "NGnrKwXzSms2qUUih/ILZ5JBqNTSa1+ZmP6flaIp6KmSElgE9qdndzS3cqjrDovwFdmwsGsLdeFgB6suw+1e9g==";
      };
    };
    "is-alphabetical-1.0.4" = {
      name = "is-alphabetical";
      packageName = "is-alphabetical";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-alphabetical/-/is-alphabetical-1.0.4.tgz";
        sha512 = "DwzsA04LQ10FHTZuL0/grVDk4rFoVH1pjAToYwBrHSxcrBIGQuXrQMtD5U1b0U2XVgKZCTLLP8u2Qxqhy3l2Vg==";
      };
    };
    "is-alphanumerical-1.0.4" = {
      name = "is-alphanumerical";
      packageName = "is-alphanumerical";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-alphanumerical/-/is-alphanumerical-1.0.4.tgz";
        sha512 = "UzoZUr+XfVz3t3v4KyGEniVL9BDRoQtY7tOyrRybkVNjDFWyo1yhXNGrrBTQxp3ib9BLAWs7k2YKBQsFRkZG9A==";
      };
    };
    "is-array-buffer-3.0.4" = {
      name = "is-array-buffer";
      packageName = "is-array-buffer";
      version = "3.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-array-buffer/-/is-array-buffer-3.0.4.tgz";
        sha512 = "wcjaerHw0ydZwfhiKbXJWLDY8A7yV7KhjQOpb83hGgGfId/aQa4TOvwyzn2PuswW2gPCYEL/nEAiSVpdOj1lXw==";
      };
    };
    "is-bigint-1.0.4" = {
      name = "is-bigint";
      packageName = "is-bigint";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-bigint/-/is-bigint-1.0.4.tgz";
        sha512 = "zB9CruMamjym81i2JZ3UMn54PKGsQzsJeo6xvN3HJJ4CAsQNB6iRutp2To77OfCNuoxspsIhzaPoO1zyCEhFOg==";
      };
    };
    "is-boolean-object-1.1.2" = {
      name = "is-boolean-object";
      packageName = "is-boolean-object";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-boolean-object/-/is-boolean-object-1.1.2.tgz";
        sha512 = "gDYaKHJmnj4aWxyj6YHyXVpdQawtVLHU5cb+eztPGczf6cjuTdwve5ZIEfgXqH4e57An1D1AKf8CZ3kYrQRqYA==";
      };
    };
    "is-buffer-2.0.5" = {
      name = "is-buffer";
      packageName = "is-buffer";
      version = "2.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-buffer/-/is-buffer-2.0.5.tgz";
        sha512 = "i2R6zNFDwgEHJyQUtJEk0XFi1i0dPFn/oqjK3/vPCcDeJvW5NQ83V8QbicfF1SupOaB0h8ntgBC2YiE7dfyctQ==";
      };
    };
    "is-callable-1.2.7" = {
      name = "is-callable";
      packageName = "is-callable";
      version = "1.2.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-callable/-/is-callable-1.2.7.tgz";
        sha512 = "1BC0BVFhS/p0qtw6enp8e+8OD0UrK0oFLztSjNzhcKA3WDuJxxAPXzPuPtKkjEY9UUoEWlX/8fgKeu2S8i9JTA==";
      };
    };
    "is-data-view-1.0.1" = {
      name = "is-data-view";
      packageName = "is-data-view";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-data-view/-/is-data-view-1.0.1.tgz";
        sha512 = "AHkaJrsUVW6wq6JS8y3JnM/GJF/9cf+k20+iDzlSaJrinEo5+7vRiteOSwBhHRiAyQATN1AmY4hwzxJKPmYf+w==";
      };
    };
    "is-date-object-1.0.5" = {
      name = "is-date-object";
      packageName = "is-date-object";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-date-object/-/is-date-object-1.0.5.tgz";
        sha512 = "9YQaSxsAiSwcvS33MBk3wTCVnWK+HhF8VZR2jRxehM16QcVOdHqPn4VPHmRK4lSr38n9JriurInLcP90xsYNfQ==";
      };
    };
    "is-decimal-1.0.4" = {
      name = "is-decimal";
      packageName = "is-decimal";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-decimal/-/is-decimal-1.0.4.tgz";
        sha512 = "RGdriMmQQvZ2aqaQq3awNA6dCGtKpiDFcOzrTWrDAT2MiWrKQVPmxLGHl7Y2nNu6led0kEyoX0enY0qXYsv9zw==";
      };
    };
    "is-hexadecimal-1.0.4" = {
      name = "is-hexadecimal";
      packageName = "is-hexadecimal";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-hexadecimal/-/is-hexadecimal-1.0.4.tgz";
        sha512 = "gyPJuv83bHMpocVYoqof5VDiZveEoGoFL8m3BXNb2VW8Xs+rz9kqO8LOQ5DH6EsuvilT1ApazU0pyl+ytbPtlw==";
      };
    };
    "is-negative-zero-2.0.3" = {
      name = "is-negative-zero";
      packageName = "is-negative-zero";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-negative-zero/-/is-negative-zero-2.0.3.tgz";
        sha512 = "5KoIu2Ngpyek75jXodFvnafB6DJgr3u8uuK0LEZJjrU19DrMD3EVERaR8sjz8CCGgpZvxPl9SuE1GMVPFHx1mw==";
      };
    };
    "is-number-object-1.0.7" = {
      name = "is-number-object";
      packageName = "is-number-object";
      version = "1.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-number-object/-/is-number-object-1.0.7.tgz";
        sha512 = "k1U0IRzLMo7ZlYIfzRu23Oh6MiIFasgpb9X76eqfFZAqwH44UI4KTBvBYIZ1dSL9ZzChTB9ShHfLkR4pdW5krQ==";
      };
    };
    "is-plain-obj-2.1.0" = {
      name = "is-plain-obj";
      packageName = "is-plain-obj";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-plain-obj/-/is-plain-obj-2.1.0.tgz";
        sha512 = "YWnfyRwxL/+SsrWYfOpUtz5b3YD+nyfkHvjbcanzk8zgyO4ASD67uVMRt8k5bM4lLMDnXfriRhOpemw+NfT1eA==";
      };
    };
    "is-regex-1.1.4" = {
      name = "is-regex";
      packageName = "is-regex";
      version = "1.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-regex/-/is-regex-1.1.4.tgz";
        sha512 = "kvRdxDsxZjhzUX07ZnLydzS1TU/TJlTUHHY4YLL87e37oUA49DfkLqgy+VjFocowy29cKvcSiu+kIv728jTTVg==";
      };
    };
    "is-shared-array-buffer-1.0.3" = {
      name = "is-shared-array-buffer";
      packageName = "is-shared-array-buffer";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-shared-array-buffer/-/is-shared-array-buffer-1.0.3.tgz";
        sha512 = "nA2hv5XIhLR3uVzDDfCIknerhx8XUKnstuOERPNNIinXG7v9u+ohXF67vxm4TPTEPU6lm61ZkwP3c9PCB97rhg==";
      };
    };
    "is-string-1.0.7" = {
      name = "is-string";
      packageName = "is-string";
      version = "1.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-string/-/is-string-1.0.7.tgz";
        sha512 = "tE2UXzivje6ofPW7l23cjDOMa09gb7xlAqG6jG5ej6uPV32TlWP3NKPigtaGeHNu9fohccRYvIiZMfOOnOYUtg==";
      };
    };
    "is-symbol-1.0.4" = {
      name = "is-symbol";
      packageName = "is-symbol";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-symbol/-/is-symbol-1.0.4.tgz";
        sha512 = "C/CPBqKWnvdcxqIARxyOh4v1UUEOCHpgDa0WYgpKDFMszcrPcffg5uhwSgPCLD2WWxmq6isisz87tzT01tuGhg==";
      };
    };
    "is-typed-array-1.1.13" = {
      name = "is-typed-array";
      packageName = "is-typed-array";
      version = "1.1.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-typed-array/-/is-typed-array-1.1.13.tgz";
        sha512 = "uZ25/bUAlUY5fR4OKT4rZQEBrzQWYV9ZJYGGsUmEJ6thodVJ1HX64ePQ6Z0qPWP+m+Uq6e9UugrE38jeYsDSMw==";
      };
    };
    "is-weakref-1.0.2" = {
      name = "is-weakref";
      packageName = "is-weakref";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-weakref/-/is-weakref-1.0.2.tgz";
        sha512 = "qctsuLZmIQ0+vSSMfoVvyFe2+GSEvnmZ2ezTup1SBse9+twCCeial6EEi3Nc2KFcf6+qz2FBPnjXsk8xhKSaPQ==";
      };
    };
    "isarray-2.0.5" = {
      name = "isarray";
      packageName = "isarray";
      version = "2.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/isarray/-/isarray-2.0.5.tgz";
        sha512 = "xHjhDr3cNBK0BzdUJSPXZntQUx/mwMS5Rw4A7lPJ90XGAO6ISP/ePDNuo0vhqOZU+UD5JoodwCAAoZQd3FeAKw==";
      };
    };
    "longest-streak-2.0.4" = {
      name = "longest-streak";
      packageName = "longest-streak";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/longest-streak/-/longest-streak-2.0.4.tgz";
        sha512 = "vM6rUVCVUJJt33bnmHiZEvr7wPT78ztX7rojL+LW51bHtLh6HTjx84LA5W4+oa6aKEJA7jJu5LR6vQRBpA5DVg==";
      };
    };
    "markdown-table-2.0.0" = {
      name = "markdown-table";
      packageName = "markdown-table";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/markdown-table/-/markdown-table-2.0.0.tgz";
        sha512 = "Ezda85ToJUBhM6WGaG6veasyym+Tbs3cMAw/ZhOPqXiYsr0jgocBV3j3nx+4lk47plLlIqjwuTm/ywVI+zjJ/A==";
      };
    };
    "mdast-util-find-and-replace-1.1.1" = {
      name = "mdast-util-find-and-replace";
      packageName = "mdast-util-find-and-replace";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/mdast-util-find-and-replace/-/mdast-util-find-and-replace-1.1.1.tgz";
        sha512 = "9cKl33Y21lyckGzpSmEQnIDjEfeeWelN5s1kUW1LwdB0Fkuq2u+4GdqcGEygYxJE8GVqCl0741bYXHgamfWAZA==";
      };
    };
    "mdast-util-footnote-0.1.7" = {
      name = "mdast-util-footnote";
      packageName = "mdast-util-footnote";
      version = "0.1.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/mdast-util-footnote/-/mdast-util-footnote-0.1.7.tgz";
        sha512 = "QxNdO8qSxqbO2e3m09KwDKfWiLgqyCurdWTQ198NpbZ2hxntdc+VKS4fDJCmNWbAroUdYnSthu+XbZ8ovh8C3w==";
      };
    };
    "mdast-util-from-markdown-0.8.5" = {
      name = "mdast-util-from-markdown";
      packageName = "mdast-util-from-markdown";
      version = "0.8.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/mdast-util-from-markdown/-/mdast-util-from-markdown-0.8.5.tgz";
        sha512 = "2hkTXtYYnr+NubD/g6KGBS/0mFmBcifAsI0yIWRiRo0PjVs6SSOSOdtzbp6kSGnShDN6G5aWZpKQ2lWRy27mWQ==";
      };
    };
    "mdast-util-frontmatter-0.2.0" = {
      name = "mdast-util-frontmatter";
      packageName = "mdast-util-frontmatter";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mdast-util-frontmatter/-/mdast-util-frontmatter-0.2.0.tgz";
        sha512 = "FHKL4w4S5fdt1KjJCwB0178WJ0evnyyQr5kXTM3wrOVpytD0hrkvd+AOOjU9Td8onOejCkmZ+HQRT3CZ3coHHQ==";
      };
    };
    "mdast-util-gfm-0.1.2" = {
      name = "mdast-util-gfm";
      packageName = "mdast-util-gfm";
      version = "0.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/mdast-util-gfm/-/mdast-util-gfm-0.1.2.tgz";
        sha512 = "NNkhDx/qYcuOWB7xHUGWZYVXvjPFFd6afg6/e2g+SV4r9q5XUcCbV4Wfa3DLYIiD+xAEZc6K4MGaE/m0KDcPwQ==";
      };
    };
    "mdast-util-gfm-autolink-literal-0.1.3" = {
      name = "mdast-util-gfm-autolink-literal";
      packageName = "mdast-util-gfm-autolink-literal";
      version = "0.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/mdast-util-gfm-autolink-literal/-/mdast-util-gfm-autolink-literal-0.1.3.tgz";
        sha512 = "GjmLjWrXg1wqMIO9+ZsRik/s7PLwTaeCHVB7vRxUwLntZc8mzmTsLVr6HW1yLokcnhfURsn5zmSVdi3/xWWu1A==";
      };
    };
    "mdast-util-gfm-strikethrough-0.2.3" = {
      name = "mdast-util-gfm-strikethrough";
      packageName = "mdast-util-gfm-strikethrough";
      version = "0.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/mdast-util-gfm-strikethrough/-/mdast-util-gfm-strikethrough-0.2.3.tgz";
        sha512 = "5OQLXpt6qdbttcDG/UxYY7Yjj3e8P7X16LzvpX8pIQPYJ/C2Z1qFGMmcw+1PZMUM3Z8wt8NRfYTvCni93mgsgA==";
      };
    };
    "mdast-util-gfm-table-0.1.6" = {
      name = "mdast-util-gfm-table";
      packageName = "mdast-util-gfm-table";
      version = "0.1.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/mdast-util-gfm-table/-/mdast-util-gfm-table-0.1.6.tgz";
        sha512 = "j4yDxQ66AJSBwGkbpFEp9uG/LS1tZV3P33fN1gkyRB2LoRL+RR3f76m0HPHaby6F4Z5xr9Fv1URmATlRRUIpRQ==";
      };
    };
    "mdast-util-gfm-task-list-item-0.1.6" = {
      name = "mdast-util-gfm-task-list-item";
      packageName = "mdast-util-gfm-task-list-item";
      version = "0.1.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/mdast-util-gfm-task-list-item/-/mdast-util-gfm-task-list-item-0.1.6.tgz";
        sha512 = "/d51FFIfPsSmCIRNp7E6pozM9z1GYPIkSy1urQ8s/o4TC22BZ7DqfHFWiqBD23bc7J3vV1Fc9O4QIHBlfuit8A==";
      };
    };
    "mdast-util-to-markdown-0.6.5" = {
      name = "mdast-util-to-markdown";
      packageName = "mdast-util-to-markdown";
      version = "0.6.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/mdast-util-to-markdown/-/mdast-util-to-markdown-0.6.5.tgz";
        sha512 = "XeV9sDE7ZlOQvs45C9UKMtfTcctcaj/pGwH8YLbMHoMOXNNCn2LsqVQOqrF1+/NU8lKDAqozme9SCXWyo9oAcQ==";
      };
    };
    "mdast-util-to-string-2.0.0" = {
      name = "mdast-util-to-string";
      packageName = "mdast-util-to-string";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mdast-util-to-string/-/mdast-util-to-string-2.0.0.tgz";
        sha512 = "AW4DRS3QbBayY/jJmD8437V1Gombjf8RSOUCMFBuo5iHi58AGEgVCKQ+ezHkZZDpAQS75hcBMpLqjpJTjtUL7w==";
      };
    };
    "micromark-2.11.4" = {
      name = "micromark";
      packageName = "micromark";
      version = "2.11.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/micromark/-/micromark-2.11.4.tgz";
        sha512 = "+WoovN/ppKolQOFIAajxi7Lu9kInbPxFuTBVEavFcL8eAfVstoc5MocPmqBeAdBOJV00uaVjegzH4+MA0DN/uA==";
      };
    };
    "micromark-extension-footnote-0.3.2" = {
      name = "micromark-extension-footnote";
      packageName = "micromark-extension-footnote";
      version = "0.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/micromark-extension-footnote/-/micromark-extension-footnote-0.3.2.tgz";
        sha512 = "gr/BeIxbIWQoUm02cIfK7mdMZ/fbroRpLsck4kvFtjbzP4yi+OPVbnukTc/zy0i7spC2xYE/dbX1Sur8BEDJsQ==";
      };
    };
    "micromark-extension-frontmatter-0.2.2" = {
      name = "micromark-extension-frontmatter";
      packageName = "micromark-extension-frontmatter";
      version = "0.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/micromark-extension-frontmatter/-/micromark-extension-frontmatter-0.2.2.tgz";
        sha512 = "q6nPLFCMTLtfsctAuS0Xh4vaolxSFUWUWR6PZSrXXiRy+SANGllpcqdXFv2z07l0Xz/6Hl40hK0ffNCJPH2n1A==";
      };
    };
    "micromark-extension-gfm-0.3.3" = {
      name = "micromark-extension-gfm";
      packageName = "micromark-extension-gfm";
      version = "0.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/micromark-extension-gfm/-/micromark-extension-gfm-0.3.3.tgz";
        sha512 = "oVN4zv5/tAIA+l3GbMi7lWeYpJ14oQyJ3uEim20ktYFAcfX1x3LNlFGGlmrZHt7u9YlKExmyJdDGaTt6cMSR/A==";
      };
    };
    "micromark-extension-gfm-autolink-literal-0.5.7" = {
      name = "micromark-extension-gfm-autolink-literal";
      packageName = "micromark-extension-gfm-autolink-literal";
      version = "0.5.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/micromark-extension-gfm-autolink-literal/-/micromark-extension-gfm-autolink-literal-0.5.7.tgz";
        sha512 = "ePiDGH0/lhcngCe8FtH4ARFoxKTUelMp4L7Gg2pujYD5CSMb9PbblnyL+AAMud/SNMyusbS2XDSiPIRcQoNFAw==";
      };
    };
    "micromark-extension-gfm-strikethrough-0.6.5" = {
      name = "micromark-extension-gfm-strikethrough";
      packageName = "micromark-extension-gfm-strikethrough";
      version = "0.6.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/micromark-extension-gfm-strikethrough/-/micromark-extension-gfm-strikethrough-0.6.5.tgz";
        sha512 = "PpOKlgokpQRwUesRwWEp+fHjGGkZEejj83k9gU5iXCbDG+XBA92BqnRKYJdfqfkrRcZRgGuPuXb7DaK/DmxOhw==";
      };
    };
    "micromark-extension-gfm-table-0.4.3" = {
      name = "micromark-extension-gfm-table";
      packageName = "micromark-extension-gfm-table";
      version = "0.4.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/micromark-extension-gfm-table/-/micromark-extension-gfm-table-0.4.3.tgz";
        sha512 = "hVGvESPq0fk6ALWtomcwmgLvH8ZSVpcPjzi0AjPclB9FsVRgMtGZkUcpE0zgjOCFAznKepF4z3hX8z6e3HODdA==";
      };
    };
    "micromark-extension-gfm-tagfilter-0.3.0" = {
      name = "micromark-extension-gfm-tagfilter";
      packageName = "micromark-extension-gfm-tagfilter";
      version = "0.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/micromark-extension-gfm-tagfilter/-/micromark-extension-gfm-tagfilter-0.3.0.tgz";
        sha512 = "9GU0xBatryXifL//FJH+tAZ6i240xQuFrSL7mYi8f4oZSbc+NvXjkrHemeYP0+L4ZUT+Ptz3b95zhUZnMtoi/Q==";
      };
    };
    "micromark-extension-gfm-task-list-item-0.3.3" = {
      name = "micromark-extension-gfm-task-list-item";
      packageName = "micromark-extension-gfm-task-list-item";
      version = "0.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/micromark-extension-gfm-task-list-item/-/micromark-extension-gfm-task-list-item-0.3.3.tgz";
        sha512 = "0zvM5iSLKrc/NQl84pZSjGo66aTGd57C1idmlWmE87lkMcXrTxg1uXa/nXomxJytoje9trP0NDLvw4bZ/Z/XCQ==";
      };
    };
    "minimist-1.2.8" = {
      name = "minimist";
      packageName = "minimist";
      version = "1.2.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimist/-/minimist-1.2.8.tgz";
        sha512 = "2yyAR8qBkN3YuheJanUpWC5U3bb5osDywNB8RzDVlDwDHbocAJveqqj1u8+SVD7jkWT4yvsHCpWqqWqAxb0zCA==";
      };
    };
    "ms-2.1.2" = {
      name = "ms";
      packageName = "ms";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-2.1.2.tgz";
        sha512 = "sGkPx+VjMtmA6MX27oA4FBFELFCZZ4S4XqeGOXCv68tT+jb3vk/RyaKWP0PTKyWtmLSM0b+adUTEvbs1PEaH2w==";
      };
    };
    "object-inspect-1.13.2" = {
      name = "object-inspect";
      packageName = "object-inspect";
      version = "1.13.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-inspect/-/object-inspect-1.13.2.tgz";
        sha512 = "IRZSRuzJiynemAXPYtPe5BoI/RESNYR7TYm50MC5Mqbd3Jmw5y790sErYw3V6SryFJD64b74qQQs9wn5Bg/k3g==";
      };
    };
    "object-keys-1.1.1" = {
      name = "object-keys";
      packageName = "object-keys";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-keys/-/object-keys-1.1.1.tgz";
        sha512 = "NuAESUOUMrlIXOfHKzD6bpPu3tYt3xvjNdRIQ+FeT0lNb4K8WR70CaDxhuNguS2XG+GjkyMwOzsN5ZktImfhLA==";
      };
    };
    "object.assign-4.1.5" = {
      name = "object.assign";
      packageName = "object.assign";
      version = "4.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/object.assign/-/object.assign-4.1.5.tgz";
        sha512 = "byy+U7gp+FVwmyzKPYhW2h5l3crpmGsxl7X2s8y43IgxvG4g3QZ6CffDtsNQy1WsmZpQbO+ybo0AlW7TY6DcBQ==";
      };
    };
    "parse-entities-2.0.0" = {
      name = "parse-entities";
      packageName = "parse-entities";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/parse-entities/-/parse-entities-2.0.0.tgz";
        sha512 = "kkywGpCcRYhqQIchaWqZ875wzpS/bMKhz5HnN3p7wveJTkTtyAB/AlnS0f8DFSqYW1T82t6yEAkEcB+A1I3MbQ==";
      };
    };
    "possible-typed-array-names-1.0.0" = {
      name = "possible-typed-array-names";
      packageName = "possible-typed-array-names";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/possible-typed-array-names/-/possible-typed-array-names-1.0.0.tgz";
        sha512 = "d7Uw+eZoloe0EHDIYoe+bQ5WXnGMOpmiZFTuMWCwpjzzkL2nTjcKiAk4hh8TjnGye2TwWOk3UXucZ+3rbmBa8Q==";
      };
    };
    "regexp.prototype.flags-1.5.2" = {
      name = "regexp.prototype.flags";
      packageName = "regexp.prototype.flags";
      version = "1.5.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/regexp.prototype.flags/-/regexp.prototype.flags-1.5.2.tgz";
        sha512 = "NcDiDkTLuPR+++OCKB0nWafEmhg/Da8aUPLPMQbK+bxKKCm1/S5he+AqYa4PlMCVBalb4/yxIRub6qkEx5yJbw==";
      };
    };
    "remark-footnotes-3.0.0" = {
      name = "remark-footnotes";
      packageName = "remark-footnotes";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/remark-footnotes/-/remark-footnotes-3.0.0.tgz";
        sha512 = "ZssAvH9FjGYlJ/PBVKdSmfyPc3Cz4rTWgZLI4iE/SX8Nt5l3o3oEjv3wwG5VD7xOjktzdwp5coac+kJV9l4jgg==";
      };
    };
    "remark-frontmatter-3.0.0" = {
      name = "remark-frontmatter";
      packageName = "remark-frontmatter";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/remark-frontmatter/-/remark-frontmatter-3.0.0.tgz";
        sha512 = "mSuDd3svCHs+2PyO29h7iijIZx4plX0fheacJcAoYAASfgzgVIcXGYSq9GFyYocFLftQs8IOmmkgtOovs6d4oA==";
      };
    };
    "remark-gfm-1.0.0" = {
      name = "remark-gfm";
      packageName = "remark-gfm";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/remark-gfm/-/remark-gfm-1.0.0.tgz";
        sha512 = "KfexHJCiqvrdBZVbQ6RopMZGwaXz6wFJEfByIuEwGf0arvITHjiKKZ1dpXujjH9KZdm1//XJQwgfnJ3lmXaDPA==";
      };
    };
    "remark-parse-9.0.0" = {
      name = "remark-parse";
      packageName = "remark-parse";
      version = "9.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/remark-parse/-/remark-parse-9.0.0.tgz";
        sha512 = "geKatMwSzEXKHuzBNU1z676sGcDcFoChMK38TgdHJNAYfFtsfHDQG7MoJAjs6sgYMqyLduCYWDIWZIxiPeafEw==";
      };
    };
    "repeat-string-1.6.1" = {
      name = "repeat-string";
      packageName = "repeat-string";
      version = "1.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/repeat-string/-/repeat-string-1.6.1.tgz";
        sha512 = "PV0dzCYDNfRi1jCDbJzpW7jNNDRuCOG/jI5ctQcGKt/clZD+YcPS3yIlWuTJMmESC8aevCFmWJy5wjAFgNqN6w==";
      };
    };
    "safe-array-concat-1.1.2" = {
      name = "safe-array-concat";
      packageName = "safe-array-concat";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/safe-array-concat/-/safe-array-concat-1.1.2.tgz";
        sha512 = "vj6RsCsWBCf19jIeHEfkRMw8DPiBb+DMXklQ/1SGDHOMlHdPUkZXFQ2YdplS23zESTijAcurb1aSgJA3AgMu1Q==";
      };
    };
    "safe-regex-test-1.0.3" = {
      name = "safe-regex-test";
      packageName = "safe-regex-test";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/safe-regex-test/-/safe-regex-test-1.0.3.tgz";
        sha512 = "CdASjNJPvRa7roO6Ra/gLYBTzYzzPyyBXxIMdGW3USQLyjWEls2RgW5UBTXaQVp+OrpeCK3bLem8smtmheoRuw==";
      };
    };
    "set-function-length-1.2.2" = {
      name = "set-function-length";
      packageName = "set-function-length";
      version = "1.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/set-function-length/-/set-function-length-1.2.2.tgz";
        sha512 = "pgRc4hJ4/sNjWCSS9AmnS40x3bNMDTknHgL5UaMBTMyJnU90EgWh1Rz+MC9eFu4BuN/UwZjKQuY/1v3rM7HMfg==";
      };
    };
    "set-function-name-2.0.2" = {
      name = "set-function-name";
      packageName = "set-function-name";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/set-function-name/-/set-function-name-2.0.2.tgz";
        sha512 = "7PGFlmtwsEADb0WYyvCMa1t+yke6daIG4Wirafur5kcf+MhUnPms1UeR0CKQdTZD81yESwMHbtn+TR+dMviakQ==";
      };
    };
    "side-channel-1.0.6" = {
      name = "side-channel";
      packageName = "side-channel";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/side-channel/-/side-channel-1.0.6.tgz";
        sha512 = "fDW/EZ6Q9RiO8eFG8Hj+7u/oW+XrPTIChwCOM2+th2A6OblDtYYIpve9m+KvI9Z4C9qSEXlaGR6bTEYHReuglA==";
      };
    };
    "string.prototype.trim-1.2.9" = {
      name = "string.prototype.trim";
      packageName = "string.prototype.trim";
      version = "1.2.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/string.prototype.trim/-/string.prototype.trim-1.2.9.tgz";
        sha512 = "klHuCNxiMZ8MlsOihJhJEBJAiMVqU3Z2nEXWfWnIqjN0gEFS9J9+IxKozWWtQGcgoa1WUZzLjKPTr4ZHNFTFxw==";
      };
    };
    "string.prototype.trimend-1.0.8" = {
      name = "string.prototype.trimend";
      packageName = "string.prototype.trimend";
      version = "1.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/string.prototype.trimend/-/string.prototype.trimend-1.0.8.tgz";
        sha512 = "p73uL5VCHCO2BZZ6krwwQE3kCzM7NKmis8S//xEC6fQonchbum4eP6kR4DLEjQFO3Wnj3Fuo8NM0kOSjVdHjZQ==";
      };
    };
    "string.prototype.trimstart-1.0.8" = {
      name = "string.prototype.trimstart";
      packageName = "string.prototype.trimstart";
      version = "1.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/string.prototype.trimstart/-/string.prototype.trimstart-1.0.8.tgz";
        sha512 = "UXSH262CSZY1tfu3G3Secr6uGLCFVPMhIqHjlgCUtCCcgihYc/xKs9djMTMUOb2j1mVSeU8EU6NWc/iQKU6Gfg==";
      };
    };
    "traverse-0.6.9" = {
      name = "traverse";
      packageName = "traverse";
      version = "0.6.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/traverse/-/traverse-0.6.9.tgz";
        sha512 = "7bBrcF+/LQzSgFmT0X5YclVqQxtv7TDJ1f8Wj7ibBu/U6BMLeOpUxuZjV7rMc44UtKxlnMFigdhFAIszSX1DMg==";
      };
    };
    "trough-1.0.5" = {
      name = "trough";
      packageName = "trough";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/trough/-/trough-1.0.5.tgz";
        sha512 = "rvuRbTarPXmMb79SmzEp8aqXNKcK+y0XaB298IXueQ8I2PsrATcPBCSPyK/dDNa2iWOhKlfNnOjdAOTBU/nkFA==";
      };
    };
    "tslib-2.8.1" = {
      name = "tslib";
      packageName = "tslib";
      version = "2.8.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/tslib/-/tslib-2.8.1.tgz";
        sha512 = "oJFu94HQb+KVduSUQL7wnpmqnfmLsOA/nAh6b6EH0wCEoK0/mPeXU6c3wKDV83MkOuHPRHtSXKKU99IBazS/2w==";
      };
    };
    "tweetnacl-1.0.3" = {
      name = "tweetnacl";
      packageName = "tweetnacl";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/tweetnacl/-/tweetnacl-1.0.3.tgz";
        sha512 = "6rt+RN7aOi1nGMyC4Xa5DdYiukl2UWCbcJft7YhxReBGQD7OAM8Pbxw6YMo4r2diNEA8FEmu32YOn9rhaiE5yw==";
      };
    };
    "typed-array-buffer-1.0.2" = {
      name = "typed-array-buffer";
      packageName = "typed-array-buffer";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/typed-array-buffer/-/typed-array-buffer-1.0.2.tgz";
        sha512 = "gEymJYKZtKXzzBzM4jqa9w6Q1Jjm7x2d+sh19AdsD4wqnMPDYyvwpsIc2Q/835kHuo3BEQ7CjelGhfTsoBb2MQ==";
      };
    };
    "typed-array-byte-length-1.0.1" = {
      name = "typed-array-byte-length";
      packageName = "typed-array-byte-length";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/typed-array-byte-length/-/typed-array-byte-length-1.0.1.tgz";
        sha512 = "3iMJ9q0ao7WE9tWcaYKIptkNBuOIcZCCT0d4MRvuuH88fEoEH62IuQe0OtraD3ebQEoTRk8XCBoknUNc1Y67pw==";
      };
    };
    "typed-array-byte-offset-1.0.2" = {
      name = "typed-array-byte-offset";
      packageName = "typed-array-byte-offset";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/typed-array-byte-offset/-/typed-array-byte-offset-1.0.2.tgz";
        sha512 = "Ous0vodHa56FviZucS2E63zkgtgrACj7omjwd/8lTEMEPFFyjfixMZ1ZXenpgCFBBt4EC1J2XsyVS2gkG0eTFA==";
      };
    };
    "typed-array-length-1.0.6" = {
      name = "typed-array-length";
      packageName = "typed-array-length";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/typed-array-length/-/typed-array-length-1.0.6.tgz";
        sha512 = "/OxDN6OtAk5KBpGb28T+HZc2M+ADtvRxXrKKbUwtsLgdoxgX13hyy7ek6bFRl5+aBs2yZzB0c4CnQfAtVypW/g==";
      };
    };
    "typedarray.prototype.slice-1.0.3" = {
      name = "typedarray.prototype.slice";
      packageName = "typedarray.prototype.slice";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/typedarray.prototype.slice/-/typedarray.prototype.slice-1.0.3.tgz";
        sha512 = "8WbVAQAUlENo1q3c3zZYuy5k9VzBQvp8AX9WOtbvyWlLM1v5JaSRmjubLjzHF4JFtptjH/5c/i95yaElvcjC0A==";
      };
    };
    "unbox-primitive-1.0.2" = {
      name = "unbox-primitive";
      packageName = "unbox-primitive";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/unbox-primitive/-/unbox-primitive-1.0.2.tgz";
        sha512 = "61pPlCD9h51VoreyJ0BReideM3MDKMKnh6+V9L08331ipq6Q8OFXZYiqP6n/tbHx4s5I9uRhcye6BrbkizkBDw==";
      };
    };
    "underscore-1.13.7" = {
      name = "underscore";
      packageName = "underscore";
      version = "1.13.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/underscore/-/underscore-1.13.7.tgz";
        sha512 = "GMXzWtsc57XAtguZgaQViUOzs0KTkk8ojr3/xAxXLITqf/3EMwxC0inyETfDFjH/Krbhuep0HNbbjI9i/q3F3g==";
      };
    };
    "unified-9.2.2" = {
      name = "unified";
      packageName = "unified";
      version = "9.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/unified/-/unified-9.2.2.tgz";
        sha512 = "Sg7j110mtefBD+qunSLO1lqOEKdrwBFBrR6Qd8f4uwkhWNlbkaqwHse6e7QvD3AP/MNoJdEDLaf8OxYyoWgorQ==";
      };
    };
    "unist-util-is-4.1.0" = {
      name = "unist-util-is";
      packageName = "unist-util-is";
      version = "4.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/unist-util-is/-/unist-util-is-4.1.0.tgz";
        sha512 = "ZOQSsnce92GrxSqlnEEseX0gi7GH9zTJZ0p9dtu87WRb/37mMPO2Ilx1s/t9vBHrFhbgweUwb+t7cIn5dxPhZg==";
      };
    };
    "unist-util-stringify-position-2.0.3" = {
      name = "unist-util-stringify-position";
      packageName = "unist-util-stringify-position";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/unist-util-stringify-position/-/unist-util-stringify-position-2.0.3.tgz";
        sha512 = "3faScn5I+hy9VleOq/qNbAd6pAx7iH5jYBMS9I1HgQVijz/4mv5Bvw5iw1sC/90CODiKo81G/ps8AJrISn687g==";
      };
    };
    "unist-util-visit-parents-3.1.1" = {
      name = "unist-util-visit-parents";
      packageName = "unist-util-visit-parents";
      version = "3.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/unist-util-visit-parents/-/unist-util-visit-parents-3.1.1.tgz";
        sha512 = "1KROIZWo6bcMrZEwiH2UrXDyalAa0uqzWCxCJj6lPOvTve2WkfgCytoDTPaMnodXh1WrXOq0haVYHj99ynJlsg==";
      };
    };
    "update-section-0.3.3" = {
      name = "update-section";
      packageName = "update-section";
      version = "0.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/update-section/-/update-section-0.3.3.tgz";
        sha512 = "BpRZMZpgXLuTiKeiu7kK0nIPwGdyrqrs6EDSaXtjD/aQ2T+qVo9a5hRC3HN3iJjCMxNT/VxoLGQ7E/OzE5ucnw==";
      };
    };
    "vfile-4.2.1" = {
      name = "vfile";
      packageName = "vfile";
      version = "4.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/vfile/-/vfile-4.2.1.tgz";
        sha512 = "O6AE4OskCG5S1emQ/4gl8zK586RqA3srz3nfK/Viy0UPToBc5Trp9BVFb1u0CjsKrAWwnpr4ifM/KBXPWwJbCA==";
      };
    };
    "vfile-message-2.0.4" = {
      name = "vfile-message";
      packageName = "vfile-message";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/vfile-message/-/vfile-message-2.0.4.tgz";
        sha512 = "DjssxRGkMvifUOJre00juHoP9DPWuzjxKuMDrhNbk2TdaYYBNMStsNhEOt3idrtI12VQYM/1+iM0KOzXi4pxwQ==";
      };
    };
    "which-boxed-primitive-1.0.2" = {
      name = "which-boxed-primitive";
      packageName = "which-boxed-primitive";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/which-boxed-primitive/-/which-boxed-primitive-1.0.2.tgz";
        sha512 = "bwZdv0AKLpplFY2KZRX6TvyuN7ojjr7lwkg6ml0roIy9YeuSr7JS372qlNW18UQYzgYK9ziGcerWqZOmEn9VNg==";
      };
    };
    "which-typed-array-1.1.15" = {
      name = "which-typed-array";
      packageName = "which-typed-array";
      version = "1.1.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/which-typed-array/-/which-typed-array-1.1.15.tgz";
        sha512 = "oV0jmFtUky6CXfkqehVvBP/LSWJ2sy4vWMioiENyJLePrBO/yKyV9OyJySfAKosh+RYkIl5zJCNZ8/4JncrpdA==";
      };
    };
    "zwitch-1.0.5" = {
      name = "zwitch";
      packageName = "zwitch";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/zwitch/-/zwitch-1.0.5.tgz";
        sha512 = "V50KMwwzqJV0NpZIZFwfOD5/lyny3WlSzRiXgA0G7VUnRlqttta1L6UQIHzd6EuBY/cHGfwTIck7w1yH6Q5zUw==";
      };
    };
  };
  args = {
    name = "purescript-cardano-transaction-builder";
    packageName = "purescript-cardano-transaction-builder";
    src = ./..;
    dependencies = [
      sources."@aws-crypto/crc32-5.2.0"
      sources."@aws-crypto/util-5.2.0"
      sources."@aws-sdk/types-3.731.0"
      sources."@mlabs-haskell/cardano-data-lite-git+ssh://git@github.com/mlabs-haskell/cardano-data-lite.git#01274415829dc56d3b136b33c27d614a5e53e71f"
      sources."@mlabs-haskell/json-bigint-2.0.0"
      sources."@noble/ed25519-2.2.3"
      sources."@noble/hashes-1.7.1"
      sources."@smithy/is-array-buffer-2.2.0"
      sources."@smithy/types-4.1.0"
      sources."@smithy/util-buffer-from-2.2.0"
      sources."@smithy/util-utf8-2.3.0"
      sources."@textlint/ast-node-types-12.6.1"
      sources."@textlint/markdown-to-ast-12.6.1"
      sources."@types/mdast-3.0.15"
      sources."@types/unist-2.0.10"
      sources."anchor-markdown-header-0.6.0"
      sources."array-buffer-byte-length-1.0.1"
      sources."arraybuffer.prototype.slice-1.0.3"
      sources."available-typed-arrays-1.0.7"
      sources."bail-1.0.5"
      sources."base58-js-2.0.0"
      sources."bech32-2.0.0"
      sources."call-bind-1.0.7"
      sources."ccount-1.1.0"
      sources."character-entities-1.2.4"
      sources."character-entities-legacy-1.1.4"
      sources."character-reference-invalid-1.1.4"
      sources."data-view-buffer-1.0.1"
      sources."data-view-byte-length-1.0.1"
      sources."data-view-byte-offset-1.0.0"
      sources."debug-4.3.6"
      sources."define-data-property-1.1.4"
      sources."define-properties-1.2.1"
      sources."doctoc-2.2.1"
      (sources."dom-serializer-1.4.1"
        // {
          dependencies = [
            sources."entities-2.2.0"
          ];
        })
      sources."domelementtype-2.3.0"
      sources."domhandler-4.3.1"
      sources."domutils-2.8.0"
      sources."emoji-regex-10.1.0"
      sources."entities-3.0.1"
      sources."es-abstract-1.23.3"
      sources."es-define-property-1.0.0"
      sources."es-errors-1.3.0"
      sources."es-object-atoms-1.0.0"
      sources."es-set-tostringtag-2.0.3"
      sources."es-to-primitive-1.2.1"
      sources."escape-string-regexp-4.0.0"
      sources."extend-3.0.2"
      sources."fault-1.0.4"
      sources."for-each-0.3.3"
      sources."format-0.2.2"
      sources."function-bind-1.1.2"
      sources."function.prototype.name-1.1.6"
      sources."functions-have-names-1.2.3"
      sources."get-intrinsic-1.2.4"
      sources."get-symbol-description-1.0.2"
      sources."globalthis-1.0.4"
      sources."gopd-1.0.1"
      sources."has-bigints-1.0.2"
      sources."has-property-descriptors-1.0.2"
      sources."has-proto-1.0.3"
      sources."has-symbols-1.0.3"
      sources."has-tostringtag-1.0.2"
      sources."hasown-2.0.2"
      sources."htmlparser2-7.2.0"
      sources."internal-slot-1.0.7"
      sources."is-alphabetical-1.0.4"
      sources."is-alphanumerical-1.0.4"
      sources."is-array-buffer-3.0.4"
      sources."is-bigint-1.0.4"
      sources."is-boolean-object-1.1.2"
      sources."is-buffer-2.0.5"
      sources."is-callable-1.2.7"
      sources."is-data-view-1.0.1"
      sources."is-date-object-1.0.5"
      sources."is-decimal-1.0.4"
      sources."is-hexadecimal-1.0.4"
      sources."is-negative-zero-2.0.3"
      sources."is-number-object-1.0.7"
      sources."is-plain-obj-2.1.0"
      sources."is-regex-1.1.4"
      sources."is-shared-array-buffer-1.0.3"
      sources."is-string-1.0.7"
      sources."is-symbol-1.0.4"
      sources."is-typed-array-1.1.13"
      sources."is-weakref-1.0.2"
      sources."isarray-2.0.5"
      sources."longest-streak-2.0.4"
      sources."markdown-table-2.0.0"
      sources."mdast-util-find-and-replace-1.1.1"
      sources."mdast-util-footnote-0.1.7"
      sources."mdast-util-from-markdown-0.8.5"
      sources."mdast-util-frontmatter-0.2.0"
      sources."mdast-util-gfm-0.1.2"
      sources."mdast-util-gfm-autolink-literal-0.1.3"
      sources."mdast-util-gfm-strikethrough-0.2.3"
      sources."mdast-util-gfm-table-0.1.6"
      sources."mdast-util-gfm-task-list-item-0.1.6"
      sources."mdast-util-to-markdown-0.6.5"
      sources."mdast-util-to-string-2.0.0"
      sources."micromark-2.11.4"
      sources."micromark-extension-footnote-0.3.2"
      sources."micromark-extension-frontmatter-0.2.2"
      sources."micromark-extension-gfm-0.3.3"
      sources."micromark-extension-gfm-autolink-literal-0.5.7"
      sources."micromark-extension-gfm-strikethrough-0.6.5"
      sources."micromark-extension-gfm-table-0.4.3"
      sources."micromark-extension-gfm-tagfilter-0.3.0"
      sources."micromark-extension-gfm-task-list-item-0.3.3"
      sources."minimist-1.2.8"
      sources."ms-2.1.2"
      sources."object-inspect-1.13.2"
      sources."object-keys-1.1.1"
      sources."object.assign-4.1.5"
      sources."parse-entities-2.0.0"
      sources."possible-typed-array-names-1.0.0"
      sources."regexp.prototype.flags-1.5.2"
      sources."remark-footnotes-3.0.0"
      sources."remark-frontmatter-3.0.0"
      sources."remark-gfm-1.0.0"
      sources."remark-parse-9.0.0"
      sources."repeat-string-1.6.1"
      sources."safe-array-concat-1.1.2"
      sources."safe-regex-test-1.0.3"
      sources."set-function-length-1.2.2"
      sources."set-function-name-2.0.2"
      sources."side-channel-1.0.6"
      sources."string.prototype.trim-1.2.9"
      sources."string.prototype.trimend-1.0.8"
      sources."string.prototype.trimstart-1.0.8"
      sources."traverse-0.6.9"
      sources."trough-1.0.5"
      sources."tslib-2.8.1"
      sources."tweetnacl-1.0.3"
      sources."typed-array-buffer-1.0.2"
      sources."typed-array-byte-length-1.0.1"
      sources."typed-array-byte-offset-1.0.2"
      sources."typed-array-length-1.0.6"
      sources."typedarray.prototype.slice-1.0.3"
      sources."unbox-primitive-1.0.2"
      sources."underscore-1.13.7"
      sources."unified-9.2.2"
      sources."unist-util-is-4.1.0"
      sources."unist-util-stringify-position-2.0.3"
      sources."unist-util-visit-parents-3.1.1"
      sources."update-section-0.3.3"
      sources."vfile-4.2.1"
      sources."vfile-message-2.0.4"
      sources."which-boxed-primitive-1.0.2"
      sources."which-typed-array-1.1.15"
      sources."zwitch-1.0.5"
    ];
    buildInputs = globalBuildInputs;
    meta = {
    };
    production = false;
    bypassCache = true;
    reconstructLock = false;
  };
in {
  args = args;
  sources = sources;
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
  nodeDependencies = nodeEnv.buildNodeDependencies (lib.overrideExisting args {
    src = stdenv.mkDerivation {
      name = args.name + "-package-json";
      src =
        nix-gitignore.gitignoreSourcePure [
          "*"
          "!package.json"
          "!package-lock.json"
        ]
        args.src;
      dontBuild = true;
      installPhase = "mkdir -p $out; cp -r ./* $out;";
    };
  });
}
